// What this does:
//   Emoji sections and search keyword mappings for the stream display emoji picker

export const EMOJI_SECTIONS: { label: string; emojis: string[] }[] = [
  { label: 'Common', emojis: ['▸', '📦', '💾', '⚙️', '🎨', '🔊', '📡', '🏷️', '🌐', '🎬', '📺', '⭐', '🔥', '✨', '💎', '🎯', '📊', '🎮', '🏆', '⚡', '🎵', '📐', '🔧', '💿', '👑', '🔒', '✅', '❌'] },
  { label: 'Symbols', emojis: ['▸', '▶', '►', '▪', '▫', '◾', '◽', '●', '○', '◆', '◇', '★', '☆', '✦', '✧', '⬥', '⬦', '⏵', '⏶', '⏷', '⟐', '⊙', '⊕', '⊘', '∞', '≈', '≠', '±', '×', '÷', '√', '∑', '∆', '∇', '∅', '∈', '⊂', '⊃', '∩', '∪', '†', '‡', '§', '¶', '©', '®', '™', '℗', '℠', '№', '℃', '℉', '‰', '‱'] },
  { label: 'Media', emojis: ['🎬', '📺', '🎥', '📽️', '🎞️', '📀', '💿', '💾', '📦', '📁', '📂', '🗂️', '🗃️', '🗄️', '📼', '📹', '🎙️', '🎧', '🎵', '🎶', '🔊', '🔉', '🔈', '🔇', '📻', '📷', '📸', '🖨️', '📠', '🎤', '🎸', '🎹', '🎷', '🎺', '🎻', '🥁', '🪘', '🎼', '🪗', '📰', '🗞️', '📖', '📚', '🔏', '🔐', '🔑', '🗝️'] },
  { label: 'Tech', emojis: ['⚙️', '🔧', '🔩', '🛠️', '📡', '📐', '💻', '🖥️', '📱', '⌨️', '🖱️', '🔌', '🔋', '💡', '🧲', '🧮', '🔬', '🔭', '📊', '📈', '📉', '🧪', '🏗️', '⛓️', '🤖', '👾', '🧬', '🦠', '🛡️', '⚔️', '🗡️', '🪃', '🏹', '💣', '🧨', '🪛', '🪚', '⛏️', '🪝', '🧰', '🪤', '📟', '📞', '☎️', '🖲️', '💽', '🖳'] },
  { label: 'Visual', emojis: ['🎨', '🌈', '🖼️', '🎭', '👁️', '🔍', '🔎', '✨', '💎', '🔥', '⚡', '💥', '🌟', '⭐', '🌙', '☀️', '🌊', '❄️', '🍃', '🌸', '🌀', '🎆', '🎇', '💫', '🪩', '🔮', '🧿', '🪬', '💠', '🔆', '🔅', '☁️', '⛅', '🌤️', '🌥️', '🌦️', '🌧️', '⛈️', '🌩️', '🌪️', '🌫️', '🌬️', '☔', '⛄', '🌍', '🌎', '🌏', '🪐'] },
  { label: 'Hearts', emojis: ['❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '🤎', '💔', '❤️‍🔥', '❤️‍🩹', '❣️', '💕', '💞', '💓', '💗', '💖', '💘', '💝', '♥️', '♡', '☮️', '☯️', '♾️', '🕉️', '✝️', '☪️', '🔯', '✡️', '♻️', '⚜️', '🪷', '☘️', '🍀', '🌹', '🌺', '🌻', '🌼', '🌷', '💐', '🪻', '🌾', '🍁', '🍂', '🎋', '🎍', '🪴'] },
  { label: 'Labels', emojis: ['🏷️', '🏴', '🏳️', '🚩', '📌', '📎', '📍', '🔖', '🔗', '🏠', '🌐', '🗺️', '🧭', '📮', '📬', '📧', '💬', '💭', '🗨️', '🗯️', '📝', '📋', '📃', '📄', '✏️', '✒️', '🖊️', '🖋️', '🖌️', '🖍️', '📏', '📐', '✂️', '🗑️', '📎', '🖇️', '📐', '📕', '📗', '📘', '📙', '📓', '📔', '📒', '🗒️', '📑', '🔎', '🏁'] },
  { label: 'Status', emojis: ['✅', '❌', '⚠️', '❓', '❗', '💯', '🆗', '🆕', '🆙', '🔴', '🟠', '🟡', '🟢', '🔵', '🟣', '⚪', '⚫', '🟤', '🔶', '🔷', '🔸', '🔹', '▪️', '▫️', '🟥', '🟧', '🟨', '🟩', '🟦', '🟪', '⬛', '⬜', '🔳', '🔲', '☑️', '✔️', '✖️', '➕', '➖', '➗', '❔', '❕', '‼️', '⁉️', '〽️', '🚫', '🚷', '⛔'] },
  { label: 'Awards', emojis: ['🏆', '🥇', '🥈', '🥉', '🎯', '🎪', '🎲', '🎮', '🕹️', '🎰', '🎳', '🎖️', '🏅', '🎗️', '👑', '💍', '💝', '🎁', '🎀', '🎊', '🎉', '🎈', '🧧', '🪅', '🏵️', '🎏', '🎑', '🧸', '🪆', '🎐', '🎃', '🎄', '🧨', '🪔', '🕯️', '🎩', '🪄', '🎪', '🧙', '🧝', '🦸', '🦹', '🤴', '👸', '🫅', '💂', '🥷', '🧛'] },
  { label: 'Arrows', emojis: ['➡️', '⬅️', '⬆️', '⬇️', '↗️', '↘️', '↙️', '↖️', '↩️', '↪️', '🔄', '🔃', '🔀', '🔁', '🔂', '⏩', '⏪', '⏫', '⏬', '▶️', '◀️', '⏭️', '⏮️', '⏸️', '⏹️', '⏺️', '⏏️', '🔼', '🔽', '⤴️', '⤵️', '🔛', '🔜', '🔝', '🔙', '🔚', '↔️', '↕️', '🔃', '🔄', '♻️', '🔰', '⚜️', '🔱', '〰️', '➰', '➿', '✳️'] },
  { label: 'People', emojis: ['😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂', '🙂', '😉', '😊', '😇', '🥰', '😍', '🤩', '😎', '🤓', '🧐', '😏', '😒', '😞', '😔', '😟', '😕', '🙁', '😤', '😠', '😡', '🤬', '😈', '👿', '💀', '☠️', '💩', '🤡', '👹', '👺', '👻', '👽', '🤖', '😺', '😸', '😹', '😻', '😼', '😽', '🙀', '😿'] },
  { label: 'Gestures', emojis: ['👍', '👎', '👊', '✊', '🤛', '🤜', '👏', '🙌', '🫶', '👐', '🤲', '🤝', '🙏', '✌️', '🤞', '🫰', '🤟', '🤘', '🤙', '🫵', '👈', '👉', '👆', '👇', '☝️', '✋', '🤚', '🖐️', '🖖', '🫱', '🫲', '🫳', '🫴', '👋', '🤏', '✍️', '💪', '🦾', '🦿', '🦵', '🦶', '👀', '👂', '🦻', '👃', '🧠', '🫀', '🫁'] },
  { label: 'Animals', emojis: ['🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐻‍❄️', '🐨', '🐯', '🦁', '🐮', '🐷', '🐸', '🐵', '🙈', '🙉', '🙊', '🐒', '🐔', '🐧', '🐦', '🐤', '🦆', '🦅', '🦉', '🦇', '🐺', '🐗', '🐴', '🦄', '🐝', '🪱', '🐛', '🦋', '🐌', '🐞', '🐜', '🪰', '🪲', '🪳', '🦟', '🦗', '🕷️', '🦂', '🐢', '🐍'] },
  { label: 'Food', emojis: ['🍎', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🫐', '🍈', '🍒', '🍑', '🥭', '🍍', '🥥', '🥝', '🍅', '🍆', '🥑', '🥦', '🥬', '🥒', '🌶️', '🫑', '🌽', '🥕', '🧄', '🧅', '🥔', '🍠', '🫘', '🥜', '🌰', '🍞', '🥐', '🥖', '🫓', '🥨', '🥯', '🥞', '🧇', '🍕', '🌭', '🍔', '🍟', '🌮', '🌯', '🫔'] },
  { label: 'Travel', emojis: ['🚗', '🚕', '🚙', '🚌', '🚎', '🏎️', '🚓', '🚑', '🚒', '🚐', '🛻', '🚚', '🚛', '🚜', '🏍️', '🛵', '🚲', '🛴', '🛹', '🛼', '🚁', '✈️', '🛩️', '🛫', '🛬', '🪂', '🚀', '🛸', '🛰️', '🚢', '⛵', '🛥️', '🚤', '⛴️', '🛳️', '⚓', '🗼', '🗽', '🗾', '🏰', '🏯', '🏟️', '🎡', '🎢', '🎠', '⛲', '🏖️', '🏝️'] },
  { label: 'Objects', emojis: ['⌚', '📱', '💻', '⌨️', '🖥️', '🖨️', '🖱️', '💽', '💾', '💿', '📀', '🎥', '📷', '📸', '📹', '📼', '🔍', '🔎', '🕯️', '💡', '🔦', '🏮', '🪔', '📔', '📕', '📖', '📗', '📘', '📙', '📚', '📓', '📒', '📃', '📜', '📄', '📰', '🗞️', '📑', '🔖', '🏷️', '💰', '🪙', '💴', '💵', '💶', '💷', '💸', '💳'] },
  { label: 'Locks', emojis: ['🔒', '🔓', '🔏', '🔐', '🔑', '🗝️', '🔨', '🪓', '⛏️', '⚒️', '🛠️', '🗡️', '⚔️', '💣', '🪃', '🏹', '🛡️', '🪚', '🔧', '🪛', '🔩', '⚙️', '🗜️', '⚖️', '🦯', '🔗', '⛓️', '🪝', '🧰', '🧲', '🪜', '🧫', '🧬', '🔬', '🔭', '📡', '💉', '🩸', '💊', '🩹', '🩻', '🩺', '🚪', '🪞', '🪟', '🛏️', '🪑', '🚿'] },
  { label: 'Flags', emojis: ['🏁', '🚩', '🎌', '🏴', '🏳️', '🏳️‍🌈', '🏳️‍⚧️', '🏴‍☠️', '🇺🇸', '🇬🇧', '🇨🇦', '🇦🇺', '🇩🇪', '🇫🇷', '🇮🇹', '🇪🇸', '🇯🇵', '🇰🇷', '🇨🇳', '🇮🇳', '🇧🇷', '🇲🇽', '🇷🇺', '🇳🇱', '🇸🇪', '🇳🇴', '🇩🇰', '🇫🇮', '🇵🇱', '🇺🇦', '🇹🇷', '🇿🇦', '🇳🇿', '🇮🇪', '🇵🇹', '🇦🇷', '🇨🇱', '🇨🇴', '🇵🇪', '🇻🇪', '🇪🇬', '🇳🇬', '🇰🇪', '🇹🇭', '🇵🇭', '🇮🇩', '🇻🇳', '🇸🇬'] },
  { label: 'Community', emojis: ['👤', '👥', '🧑', '👨', '👩', '🧒', '👦', '👧', '👶', '🧓', '👴', '👵', '🗣️', '🗣', '👫', '👬', '👭', '💑', '👪', '👨‍👩‍👦', '👨‍👩‍👧', '👨‍👩‍👧‍👦', '👨‍👦', '👩‍👦', '👩‍👧', '🧑‍🤝‍🧑', '👷', '👮', '🕵️', '💂', '👩‍⚕️', '👨‍⚕️', '👩‍🎓', '👨‍🎓', '👩‍💻', '👨‍💻', '👩‍🔬', '👨‍🔬', '👩‍🎨', '👨‍🎨', '👩‍🚀', '👨‍🚀', '👩‍🍳', '👨‍🍳', '🧑‍🏫', '🧑‍⚖️', '🤱', '🫄'] },
  { label: 'Zodiac', emojis: ['♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓', '⛎', '🔯', '♠️', '♣️', '♥️', '♦️', '🃏', '🀄', '🎴', '🔮', '🧿', '🪬', '☸️', '⚛️', '🕎', '☦️', '☪️', '✡️', '🔱', '⚜️', '〽️', '㊗️', '㊙️', '🈴', '🈵', '🈹', '🈲', '🈶', '🈚', '🈸', '🈺', '🈷️', '🆎', '🅰️', '🅱️', '🅾️'] },
];

export const EMOJI_NAMES: Record<string, string> = {
  '▸': 'play triangle arrow right pointer', '▶': 'play right arrow', '►': 'play right arrow pointer', '▪': 'square black small', '▫': 'square white small',
  '◾': 'square black medium', '◽': 'square white medium', '●': 'circle black dot', '○': 'circle white', '◆': 'diamond black',
  '◇': 'diamond white', '★': 'star black filled', '☆': 'star white outline', '✦': 'star four pointed', '✧': 'star sparkle',
  '⬥': 'diamond black medium', '⬦': 'diamond white medium', '⏵': 'play right triangle', '⏶': 'up triangle', '⏷': 'down triangle',
  '⟐': 'diamond dot', '⊙': 'circle dot target', '⊕': 'circle plus add', '⊘': 'circle slash empty',
  '∞': 'infinity forever', '≈': 'approximately equal', '≠': 'not equal different', '±': 'plus minus', '×': 'multiply times cross',
  '÷': 'divide division', '√': 'square root math', '∑': 'sum sigma total', '∆': 'delta triangle change', '∇': 'nabla gradient',
  '∅': 'empty set null void', '∈': 'element member of', '⊂': 'subset', '⊃': 'superset', '∩': 'intersection and',
  '∪': 'union or', '†': 'dagger cross', '‡': 'double dagger', '§': 'section sign', '¶': 'paragraph pilcrow',
  '©': 'copyright', '®': 'registered trademark', '™': 'trademark', '℗': 'sound recording copyright phonogram',
  '℠': 'service mark', '№': 'numero number', '℃': 'celsius temperature', '℉': 'fahrenheit temperature', '‰': 'per mille thousand', '‱': 'per ten thousand basis point',
  '🎬': 'movie clapper film cinema', '📺': 'tv television screen monitor', '🎥': 'camera movie video film', '📽️': 'projector film movie',
  '🎞️': 'film frames strip', '📀': 'dvd disc optical', '💿': 'cd disc compact', '💾': 'floppy disk save',
  '📦': 'package box pack', '📁': 'folder file directory', '📂': 'folder open file', '🗂️': 'dividers card index',
  '🗃️': 'card file box', '🗄️': 'cabinet file drawer', '📼': 'vhs tape video cassette', '📹': 'camcorder video camera',
  '🎙️': 'microphone studio mic', '🎧': 'headphones audio music listen', '🎵': 'music note audio sound', '🎶': 'music notes audio sound melody',
  '🔊': 'speaker sound audio loud volume', '🔉': 'speaker medium volume sound', '🔈': 'speaker low volume sound', '🔇': 'muted speaker silent',
  '📻': 'radio broadcast fm am', '📷': 'camera photo picture', '📸': 'camera flash photo', '🖨️': 'printer print',
  '📠': 'fax machine', '🎤': 'microphone karaoke sing', '🎸': 'guitar music rock', '🎹': 'piano keyboard music keys',
  '🎷': 'saxophone jazz music', '🎺': 'trumpet brass music', '🎻': 'violin fiddle strings music', '🥁': 'drum percussion beat',
  '🪘': 'long drum bongo', '🎼': 'musical score sheet', '🪗': 'accordion music', '📰': 'newspaper news press',
  '🗞️': 'rolled newspaper news', '📖': 'open book read', '📚': 'books stack library', '🔏': 'locked pen secure',
  '🔐': 'locked key secure', '🔑': 'key unlock access', '🗝️': 'old key vintage skeleton',
  '⚙️': 'gear settings config cog', '🔧': 'wrench tool fix repair', '🔩': 'nut bolt screw', '🛠️': 'hammer wrench tools build',
  '📡': 'satellite antenna signal dish', '📐': 'ruler triangle measure angle', '💻': 'laptop computer portable', '🖥️': 'desktop computer monitor screen',
  '📱': 'phone mobile smartphone cell', '⌨️': 'keyboard type input', '🖱️': 'mouse computer click cursor', '🔌': 'plug electric power cord',
  '🔋': 'battery power charge energy', '💡': 'lightbulb idea bright lamp', '🧲': 'magnet attract', '🧮': 'abacus math calculate',
  '🔬': 'microscope science zoom', '🔭': 'telescope space astronomy', '📊': 'chart bar graph stats data', '📈': 'chart up trending growth',
  '📉': 'chart down declining loss', '🧪': 'test tube science lab experiment', '🏗️': 'construction building crane site', '⛓️': 'chain link connected',
  '🤖': 'robot bot android machine ai', '👾': 'alien monster space invader game', '🧬': 'dna genetics science helix',
  '🦠': 'microbe virus bacteria germ', '🛡️': 'shield protect defense guard', '⚔️': 'swords crossed battle fight',
  '🗡️': 'dagger knife blade sword', '🪃': 'boomerang return throw', '🏹': 'bow arrow archery',
  '💣': 'bomb explosive', '🧨': 'firecracker dynamite explosive', '🪛': 'screwdriver tool flathead',
  '🪚': 'saw carpentry tool wood', '⛏️': 'pick mining tool', '🪝': 'hook catch grab',
  '🧰': 'toolbox toolkit repair', '🪤': 'mousetrap trap catch', '📟': 'pager beeper',
  '📞': 'telephone receiver phone call', '☎️': 'telephone rotary phone vintage', '🖲️': 'trackball input device', '💽': 'minidisc computer data', '🖳': 'screen old computer',
  '🎨': 'palette art color paint brush', '🌈': 'rainbow colors spectrum', '🖼️': 'frame picture painting art', '🎭': 'masks theater drama comedy tragedy',
  '👁️': 'eye look see watch vision', '🔍': 'magnify search zoom glass left', '🔎': 'magnify search zoom glass right', '✨': 'sparkles stars magic shine glitter',
  '💎': 'gem diamond jewel precious crystal', '🔥': 'fire hot flame lit burn', '⚡': 'lightning bolt electric zap thunder', '💥': 'boom explosion bang collision crash',
  '🌟': 'star glowing bright shine', '⭐': 'star yellow gold favorite', '🌙': 'moon crescent night dark', '☀️': 'sun bright day sunny light',
  '🌊': 'wave water ocean sea surf', '❄️': 'snowflake cold winter ice frozen', '🍃': 'leaf wind nature green', '🌸': 'blossom flower cherry pink spring',
  '🌀': 'cyclone spiral swirl storm', '🎆': 'fireworks celebration night', '🎇': 'sparkler firework celebration', '💫': 'dizzy star shooting spinning',
  '🪩': 'disco ball mirror party dance', '🔮': 'crystal ball fortune magic predict', '🧿': 'nazar amulet evil eye protection', '🪬': 'hamsa hand protection',
  '💠': 'diamond dot blue gem', '🔆': 'bright high brightness sun', '🔅': 'dim low brightness sun',
  '☁️': 'cloud sky overcast', '⛅': 'sun behind cloud partly cloudy', '🌤️': 'sun small cloud', '🌥️': 'sun large cloud',
  '🌦️': 'sun cloud rain', '🌧️': 'cloud rain', '⛈️': 'cloud lightning rain storm', '🌩️': 'cloud lightning thunder',
  '🌪️': 'tornado twister storm', '🌫️': 'fog mist haze', '🌬️': 'wind blowing face', '☔': 'umbrella rain',
  '⛄': 'snowman winter cold', '🌍': 'globe earth europe africa world', '🌎': 'globe earth americas world', '🌏': 'globe earth asia australia world', '🪐': 'planet ringed saturn space',
  '❤️': 'red heart love', '🧡': 'orange heart', '💛': 'yellow heart', '💚': 'green heart',
  '💙': 'blue heart', '💜': 'purple heart', '🖤': 'black heart dark', '🤍': 'white heart',
  '🤎': 'brown heart', '💔': 'broken heart sad', '❤️‍🔥': 'heart fire burning passion', '❤️‍🩹': 'mending heart healing',
  '❣️': 'heart exclamation heavy', '💕': 'two hearts love', '💞': 'revolving hearts spinning', '💓': 'beating heart pulse',
  '💗': 'growing heart expanding', '💖': 'sparkling heart shine', '💘': 'heart arrow cupid love', '💝': 'heart ribbon gift',
  '♥️': 'heart suit card', '♡': 'white heart suit outline', '☮️': 'peace sign symbol', '☯️': 'yin yang balance',
  '♾️': 'infinity forever eternal', '🕉️': 'om hindu sacred', '✝️': 'cross latin christian', '☪️': 'star crescent islam',
  '🔯': 'star david hexagram', '✡️': 'star david judaism', '♻️': 'recycle green environment', '⚜️': 'fleur de lis french',
  '🪷': 'lotus flower zen', '☘️': 'shamrock clover irish', '🍀': 'four leaf clover lucky', '🌹': 'rose flower red romance',
  '🌺': 'hibiscus flower tropical', '🌻': 'sunflower yellow happy', '🌼': 'blossom flower white', '🌷': 'tulip flower spring',
  '💐': 'bouquet flowers bunch', '🪻': 'hyacinth flower purple', '🌾': 'rice sheaf grain wheat', '🍁': 'maple leaf fall autumn canada',
  '🍂': 'fallen leaf autumn brown', '🎋': 'tanabata tree bamboo', '🎍': 'pine decoration new year', '🪴': 'potted plant houseplant',
  '🏷️': 'tag label price', '🏴': 'flag black', '🏳️': 'flag white surrender', '🚩': 'flag red triangular warning',
  '📌': 'pin pushpin tack', '📎': 'paperclip clip attach', '📍': 'pin round location map', '🔖': 'bookmark ribbon mark',
  '🔗': 'link chain url connect', '🏠': 'house home', '🌐': 'globe earth world web internet', '🗺️': 'map world atlas',
  '🧭': 'compass navigation direction north', '📮': 'mailbox post letter', '📬': 'mailbox mail letter open', '📧': 'email letter message at',
  '💬': 'speech bubble chat talk text', '💭': 'thought bubble think idea', '🗨️': 'speech balloon left talk', '🗯️': 'anger bubble right mad',
  '📝': 'memo note write pencil', '📋': 'clipboard list checklist', '📃': 'page document curl paper', '📄': 'page document facing paper',
  '✏️': 'pencil write draw', '✒️': 'black nib pen ink', '🖊️': 'pen ballpoint write', '🖋️': 'fountain pen ink write',
  '🖌️': 'paintbrush art paint', '🖍️': 'crayon draw color', '📏': 'ruler straight measure', '✂️': 'scissors cut snip',
  '🗑️': 'trash wastebasket garbage delete', '🖇️': 'linked paperclips attach', '📕': 'closed book red',
  '📗': 'green book', '📘': 'blue book', '📙': 'orange book', '📓': 'notebook cover',
  '📔': 'notebook decorative', '📒': 'ledger notebook', '🗒️': 'spiral notepad', '📑': 'bookmark tabs', '🏁': 'checkered flag finish race',
  '✅': 'check mark green yes done complete', '❌': 'cross mark red no reject', '⚠️': 'warning alert caution triangle', '❓': 'question mark red',
  '❗': 'exclamation mark alert red', '💯': 'hundred percent score perfect', '🆗': 'ok button approve', '🆕': 'new button fresh',
  '🆙': 'up button upgrade', '🔴': 'red circle dot stop', '🟠': 'orange circle dot', '🟡': 'yellow circle dot',
  '🟢': 'green circle dot go', '🔵': 'blue circle dot', '🟣': 'purple circle dot', '⚪': 'white circle dot empty',
  '⚫': 'black circle dot full', '🟤': 'brown circle dot', '🔶': 'orange diamond large', '🔷': 'blue diamond large',
  '🔸': 'orange diamond small', '🔹': 'blue diamond small', '▪️': 'black square small', '▫️': 'white square small',
  '🟥': 'red square large', '🟧': 'orange square large', '🟨': 'yellow square large', '🟩': 'green square large',
  '🟦': 'blue square large', '🟪': 'purple square large', '⬛': 'black large square', '⬜': 'white large square',
  '🔳': 'white square button outline', '🔲': 'black square button', '☑️': 'ballot check box', '✔️': 'check mark heavy done',
  '✖️': 'multiplication mark heavy cross', '➕': 'plus add heavy', '➖': 'minus subtract heavy', '➗': 'division divide heavy',
  '❔': 'question mark white', '❕': 'exclamation mark white', '‼️': 'double exclamation', '⁉️': 'exclamation question mark',
  '〽️': 'part alternation mark wavy', '🚫': 'prohibited forbidden no entry', '🚷': 'no pedestrians', '⛔': 'no entry stop',
  '🏆': 'trophy winner cup award champion', '🥇': 'gold medal first place winner', '🥈': 'silver medal second place', '🥉': 'bronze medal third place',
  '🎯': 'target bullseye dart direct hit', '🎪': 'circus tent show', '🎲': 'dice game random chance', '🎮': 'game controller gamepad video',
  '🕹️': 'joystick arcade game retro', '🎰': 'slot machine casino jackpot', '🎳': 'bowling ball pin strike', '🎖️': 'military medal honor',
  '🏅': 'sports medal award gold', '🎗️': 'ribbon reminder awareness', '👑': 'crown king queen royal golden', '💍': 'ring diamond wedding gem',
  '🎁': 'gift present box wrapped surprise', '🎀': 'ribbon bow pink decoration', '🎊': 'confetti ball party celebration', '🎉': 'party popper confetti celebrate',
  '🎈': 'balloon party red', '🧧': 'red envelope lucky money', '🪅': 'pinata party candy', '🏵️': 'rosette flower award',
  '🎏': 'carp streamer koinobori fish', '🎑': 'moon ceremony viewing', '🧸': 'teddy bear toy stuffed', '🪆': 'nesting dolls matryoshka russian',
  '🎐': 'wind chime bell', '🎃': 'jack o lantern halloween pumpkin', '🎄': 'christmas tree holiday', '🪔': 'diya lamp oil',
  '🕯️': 'candle light flame wax', '🎩': 'top hat magic gentleman', '🪄': 'magic wand wizard spell', '🧙': 'mage wizard magic',
  '🧝': 'elf fantasy', '🦸': 'superhero cape hero', '🦹': 'supervillain evil', '🤴': 'prince royal boy',
  '👸': 'princess royal girl', '🫅': 'person crown royal', '💂': 'guard royal british', '🥷': 'ninja stealth warrior', '🧛': 'vampire dracula fangs',
  '➡️': 'arrow right', '⬅️': 'arrow left', '⬆️': 'arrow up', '⬇️': 'arrow down',
  '↗️': 'arrow upper right northeast', '↘️': 'arrow lower right southeast', '↙️': 'arrow lower left southwest', '↖️': 'arrow upper left northwest',
  '↩️': 'arrow return left reply back', '↪️': 'arrow return right forward', '🔄': 'arrow rotate refresh sync reload', '🔃': 'arrow clockwise rotate spin',
  '🔀': 'shuffle random twisted arrows', '🔁': 'repeat loop arrows cycle', '🔂': 'repeat single loop once', '⏩': 'fast forward skip ahead',
  '⏪': 'rewind fast backward back', '⏫': 'fast up double arrow', '⏬': 'fast down double arrow', '▶️': 'play button right start',
  '◀️': 'reverse button left back', '⏭️': 'next track skip forward', '⏮️': 'previous track skip back', '⏸️': 'pause button stop',
  '⏹️': 'stop button square end', '⏺️': 'record button circle red', '⏏️': 'eject button up', '🔼': 'upward triangle button',
  '🔽': 'downward triangle button', '⤴️': 'arrow curving up right', '⤵️': 'arrow curving down right', '🔛': 'on arrow mark',
  '🔜': 'soon arrow coming', '🔝': 'top arrow up', '🔙': 'back arrow left', '🔚': 'end arrow right',
  '↔️': 'left right arrow horizontal', '↕️': 'up down arrow vertical', '🔰': 'japanese beginner symbol leaf', '🔱': 'trident emblem anchor',
  '〰️': 'wavy dash squiggly', '➰': 'curly loop', '➿': 'double curly loop', '✳️': 'eight spoked asterisk star',
  '😀': 'grinning face happy smile', '😃': 'grinning face big eyes happy', '😄': 'grinning face smiling eyes happy', '😁': 'beaming face smiling eyes grin',
  '😆': 'grinning squinting face laugh', '😅': 'grinning face sweat nervous', '🤣': 'rolling floor laughing rofl', '😂': 'face tears joy laughing crying',
  '🙂': 'slightly smiling face', '😉': 'winking face wink', '😊': 'smiling face smiling eyes blush', '😇': 'smiling face halo angel innocent',
  '🥰': 'smiling face hearts love', '😍': 'heart eyes face love', '🤩': 'star struck face amazing wow', '😎': 'smiling face sunglasses cool',
  '🤓': 'nerd face glasses smart', '🧐': 'monocle face think', '😏': 'smirking face smirk', '😒': 'unamused face meh',
  '😞': 'disappointed face sad down', '😔': 'pensive face sad thoughtful', '😟': 'worried face concern', '😕': 'confused face unsure',
  '🙁': 'slightly frowning face sad', '😤': 'huffing face angry steam', '😠': 'angry face mad', '😡': 'pouting face rage red angry',
  '🤬': 'face symbols mouth swearing', '😈': 'smiling face horns devil', '👿': 'angry face horns devil', '💀': 'skull dead death skeleton',
  '☠️': 'skull crossbones poison death', '💩': 'pile poop poo', '🤡': 'clown face', '👹': 'ogre japanese monster',
  '👺': 'goblin japanese monster', '👻': 'ghost halloween boo', '👽': 'alien extraterrestrial ufo',
  '😺': 'cat grinning face happy', '😸': 'cat grinning eyes happy', '😹': 'cat tears joy laugh', '😻': 'cat heart eyes love',
  '😼': 'cat wry smile smirk', '😽': 'cat kissing face', '🙀': 'cat weary screaming', '😿': 'cat crying face sad',
  '👍': 'thumbs up good approve like', '👎': 'thumbs down bad disapprove dislike', '👊': 'fist bump punch', '✊': 'raised fist solidarity power',
  '🤛': 'left fist bump', '🤜': 'right fist bump', '👏': 'clapping hands applause bravo', '🙌': 'raising hands celebration hooray',
  '🫶': 'heart hands love', '👐': 'open hands hug', '🤲': 'palms up together prayer', '🤝': 'handshake deal agree',
  '🙏': 'folded hands pray please thank', '✌️': 'victory peace sign two', '🤞': 'crossed fingers luck hope', '🫰': 'hand index thumb crossed money',
  '🤟': 'love you gesture rock', '🤘': 'sign horns rock metal', '🤙': 'call me hand shaka', '🫵': 'index pointing viewer you',
  '👈': 'pointing left index finger', '👉': 'pointing right index finger', '👆': 'pointing up index finger', '👇': 'pointing down index finger',
  '☝️': 'index pointing up one', '✋': 'raised hand high five stop', '🤚': 'raised back hand', '🖐️': 'hand splayed fingers spread',
  '🖖': 'vulcan salute spock', '🫱': 'rightward hand palm', '🫲': 'leftward hand palm', '🫳': 'palm down hand',
  '🫴': 'palm up hand offer', '👋': 'waving hand hello bye wave', '🤏': 'pinching hand small tiny little', '✍️': 'writing hand pen',
  '💪': 'flexed biceps strong muscle arm', '🦾': 'mechanical arm prosthetic robot', '🦿': 'mechanical leg prosthetic', '🦵': 'leg kick',
  '🦶': 'foot step', '👀': 'eyes looking watching', '👂': 'ear listen hearing', '🦻': 'ear hearing aid',
  '👃': 'nose smell sniff', '🧠': 'brain think smart mind', '🫀': 'anatomical heart organ', '🫁': 'lungs breathe organ',
  '🐶': 'dog face puppy', '🐱': 'cat face kitten', '🐭': 'mouse face rat', '🐹': 'hamster face pet',
  '🐰': 'rabbit face bunny', '🦊': 'fox face', '🐻': 'bear face', '🐼': 'panda face bear',
  '🐻‍❄️': 'polar bear arctic white', '🐨': 'koala face australia', '🐯': 'tiger face', '🦁': 'lion face king',
  '🐮': 'cow face moo', '🐷': 'pig face oink', '🐸': 'frog face', '🐵': 'monkey face',
  '🙈': 'see no evil monkey', '🙉': 'hear no evil monkey', '🙊': 'speak no evil monkey', '🐒': 'monkey primate',
  '🐔': 'chicken hen rooster', '🐧': 'penguin bird arctic', '🐦': 'bird tweet', '🐤': 'baby chick bird',
  '🦆': 'duck bird quack', '🦅': 'eagle bird raptor', '🦉': 'owl bird night wise', '🦇': 'bat flying night vampire',
  '🐺': 'wolf face howl', '🐗': 'boar pig wild', '🐴': 'horse face', '🦄': 'unicorn magical horn',
  '🐝': 'honeybee bee buzz', '🪱': 'worm', '🐛': 'bug caterpillar insect', '🦋': 'butterfly insect wings',
  '🐌': 'snail slow shell', '🐞': 'ladybug beetle insect', '🐜': 'ant insect bug', '🪰': 'fly insect bug',
  '🪲': 'beetle insect bug', '🪳': 'cockroach bug insect', '🦟': 'mosquito bug insect bite', '🦗': 'cricket insect chirp',
  '🕷️': 'spider web bug insect', '🦂': 'scorpion sting', '🐢': 'turtle tortoise slow shell', '🐍': 'snake slither',
  '🍎': 'red apple fruit', '🍐': 'pear fruit green', '🍊': 'orange tangerine fruit', '🍋': 'lemon citrus yellow',
  '🍌': 'banana fruit yellow', '🍉': 'watermelon fruit summer', '🍇': 'grapes purple fruit', '🍓': 'strawberry fruit red',
  '🫐': 'blueberries fruit blue', '🍈': 'melon fruit green', '🍒': 'cherries fruit red', '🍑': 'peach fruit',
  '🥭': 'mango fruit tropical', '🍍': 'pineapple fruit tropical', '🥥': 'coconut tropical', '🥝': 'kiwi fruit green',
  '🍅': 'tomato red vegetable', '🍆': 'eggplant aubergine purple', '🥑': 'avocado green fruit', '🥦': 'broccoli vegetable green',
  '🥬': 'leafy green vegetable lettuce', '🥒': 'cucumber pickle green', '🌶️': 'hot pepper chili spicy', '🫑': 'bell pepper vegetable',
  '🌽': 'corn cob maize', '🥕': 'carrot vegetable orange', '🧄': 'garlic vegetable cooking', '🧅': 'onion vegetable cooking',
  '🥔': 'potato vegetable', '🍠': 'sweet potato roasted', '🫘': 'beans legume', '🥜': 'peanuts nuts groundnut',
  '🌰': 'chestnut nut acorn', '🍞': 'bread loaf toast', '🥐': 'croissant pastry french', '🥖': 'baguette french bread',
  '🫓': 'flatbread naan pita', '🥨': 'pretzel snack twisted', '🥯': 'bagel bread round', '🥞': 'pancakes breakfast stack',
  '🧇': 'waffle breakfast grid', '🍕': 'pizza slice cheese', '🌭': 'hot dog sausage', '🍔': 'hamburger burger cheeseburger',
  '🍟': 'french fries chips potato', '🌮': 'taco mexican food', '🌯': 'burrito wrap mexican', '🫔': 'tamale mexican food',
  '🚗': 'car automobile sedan red', '🚕': 'taxi cab yellow car', '🚙': 'suv sport utility vehicle blue', '🚌': 'bus public transit',
  '🚎': 'trolleybus electric bus', '🏎️': 'racing car formula speed', '🚓': 'police car emergency', '🚑': 'ambulance emergency medical',
  '🚒': 'fire engine truck emergency', '🚐': 'minibus van', '🛻': 'pickup truck', '🚚': 'delivery truck moving',
  '🚛': 'articulated lorry semi trailer', '🚜': 'tractor farm', '🏍️': 'motorcycle motorbike racing', '🛵': 'motor scooter vespa',
  '🚲': 'bicycle bike cycling', '🛴': 'kick scooter', '🛹': 'skateboard', '🛼': 'roller skate',
  '🚁': 'helicopter chopper fly', '✈️': 'airplane plane fly travel', '🛩️': 'small airplane plane', '🛫': 'airplane departure takeoff',
  '🛬': 'airplane arrival landing', '🪂': 'parachute skydive', '🚀': 'rocket space launch blast', '🛸': 'flying saucer ufo alien',
  '🛰️': 'satellite space orbit', '🚢': 'ship cruise boat', '⛵': 'sailboat sailing wind', '🛥️': 'motor boat speedboat',
  '🚤': 'speedboat fast boat', '⛴️': 'ferry boat transport', '🛳️': 'passenger ship cruise liner', '⚓': 'anchor ship nautical',
  '🗼': 'tokyo tower landmark', '🗽': 'statue liberty new york', '🗾': 'map japan', '🏰': 'castle european kingdom',
  '🏯': 'japanese castle', '🏟️': 'stadium arena sports', '🎡': 'ferris wheel amusement', '🎢': 'roller coaster amusement',
  '🎠': 'carousel horse merry go round', '⛲': 'fountain water park', '🏖️': 'beach umbrella sun', '🏝️': 'desert island tropical',
  '⌚': 'watch time wrist clock', '💰': 'money bag rich cash', '🪙': 'coin money gold', '💴': 'yen banknote money japan',
  '💵': 'dollar banknote money us', '💶': 'euro banknote money', '💷': 'pound banknote money uk', '💸': 'money wings flying away',
  '💳': 'credit card payment bank', '🔒': 'locked padlock secure closed', '🔓': 'unlocked padlock open',
  '🔨': 'hammer tool nail build', '🪓': 'axe chop wood', '⚒️': 'hammer pick mining tool', '🗜️': 'compression clamp vise',
  '⚖️': 'balance scale justice law', '🦯': 'white cane blind accessibility', '🪜': 'ladder climb stairs', '🧫': 'petri dish science biology',
  '💉': 'syringe needle injection vaccine', '🩸': 'drop blood donate', '💊': 'pill medicine drug capsule', '🩹': 'bandage adhesive plaster',
  '🩻': 'xray skeleton medical', '🩺': 'stethoscope doctor medical', '🚪': 'door enter exit', '🪞': 'mirror reflection',
  '🪟': 'window glass pane', '🛏️': 'bed sleep room', '🪑': 'chair seat sit', '🚿': 'shower water bath clean',
  '📜': 'scroll parchment old document',
  '🎌': 'crossed flags japan', '🏳️‍🌈': 'rainbow flag pride lgbtq',
  '🏳️‍⚧️': 'transgender flag pride', '🏴‍☠️': 'pirate flag skull crossbones jolly roger',
  '🇺🇸': 'flag united states america usa', '🇬🇧': 'flag united kingdom britain uk', '🇨🇦': 'flag canada maple leaf', '🇦🇺': 'flag australia',
  '🇩🇪': 'flag germany german', '🇫🇷': 'flag france french', '🇮🇹': 'flag italy italian', '🇪🇸': 'flag spain spanish',
  '🇯🇵': 'flag japan japanese', '🇰🇷': 'flag south korea korean', '🇨🇳': 'flag china chinese', '🇮🇳': 'flag india indian',
  '🇧🇷': 'flag brazil brazilian', '🇲🇽': 'flag mexico mexican', '🇷🇺': 'flag russia russian', '🇳🇱': 'flag netherlands dutch',
  '🇸🇪': 'flag sweden swedish', '🇳🇴': 'flag norway norwegian', '🇩🇰': 'flag denmark danish', '🇫🇮': 'flag finland finnish',
  '🇵🇱': 'flag poland polish', '🇺🇦': 'flag ukraine ukrainian', '🇹🇷': 'flag turkey turkish', '🇿🇦': 'flag south africa',
  '🇳🇿': 'flag new zealand', '🇮🇪': 'flag ireland irish', '🇵🇹': 'flag portugal portuguese', '🇦🇷': 'flag argentina',
  '🇨🇱': 'flag chile', '🇨🇴': 'flag colombia', '🇵🇪': 'flag peru', '🇻🇪': 'flag venezuela',
  '🇪🇬': 'flag egypt', '🇳🇬': 'flag nigeria', '🇰🇪': 'flag kenya', '🇹🇭': 'flag thailand thai',
  '🇵🇭': 'flag philippines', '🇮🇩': 'flag indonesia', '🇻🇳': 'flag vietnam', '🇸🇬': 'flag singapore',
  '👤': 'person silhouette user profile', '👥': 'people silhouette group users', '🧑': 'person adult gender neutral', '👨': 'man male guy',
  '👩': 'woman female lady', '🧒': 'child kid young', '👦': 'boy male child young', '👧': 'girl female child young',
  '👶': 'baby infant newborn', '🧓': 'older person elderly senior', '👴': 'old man elderly grandfather', '👵': 'old woman elderly grandmother',
  '🗣️': 'speaking head talking voice language', '🗣': 'speaking head talking voice language', '👫': 'couple man woman holding hands', '👬': 'men holding hands couple',
  '👭': 'women holding hands couple', '💑': 'couple heart love romance', '👪': 'family parents child', '👨‍👩‍👦': 'family man woman boy',
  '👨‍👩‍👧': 'family man woman girl', '👨‍👩‍👧‍👦': 'family man woman girl boy', '👨‍👦': 'family man boy father son', '👩‍👦': 'family woman boy mother son',
  '👩‍👧': 'family woman girl mother daughter', '🧑‍🤝‍🧑': 'people holding hands together community', '👷': 'construction worker builder hard hat', '👮': 'police officer cop law',
  '🕵️': 'detective spy investigate sleuth', '👩‍⚕️': 'woman health worker doctor nurse', '👨‍⚕️': 'man health worker doctor nurse',
  '👩‍🎓': 'woman student graduate education', '👨‍🎓': 'man student graduate education', '👩‍💻': 'woman technologist coder developer', '👨‍💻': 'man technologist coder developer',
  '👩‍🔬': 'woman scientist researcher lab', '👨‍🔬': 'man scientist researcher lab', '👩‍🎨': 'woman artist painter creative', '👨‍🎨': 'man artist painter creative',
  '👩‍🚀': 'woman astronaut space nasa', '👨‍🚀': 'man astronaut space nasa', '👩‍🍳': 'woman cook chef kitchen', '👨‍🍳': 'man cook chef kitchen',
  '🧑‍🏫': 'teacher instructor educator professor', '🧑‍⚖️': 'judge justice court law', '🤱': 'breast feeding nursing mother baby', '🫄': 'pregnant person expecting',
  '♈': 'aries zodiac ram', '♉': 'taurus zodiac bull', '♊': 'gemini zodiac twins', '♋': 'cancer zodiac crab',
  '♌': 'leo zodiac lion', '♍': 'virgo zodiac maiden', '♎': 'libra zodiac scales', '♏': 'scorpio zodiac scorpion',
  '♐': 'sagittarius zodiac archer', '♑': 'capricorn zodiac goat', '♒': 'aquarius zodiac water bearer', '♓': 'pisces zodiac fish',
  '⛎': 'ophiuchus zodiac serpent', '♠️': 'spade suit card black', '♣️': 'club suit card black', '♦️': 'diamond suit card red',
  '🃏': 'joker card wild', '🀄': 'mahjong red dragon tile', '🎴': 'flower playing cards hanafuda', '☸️': 'wheel dharma buddhism',
  '⚛️': 'atom symbol science nuclear', '🕎': 'menorah candelabrum hanukkah', '☦️': 'orthodox cross',
  '㊗️': 'congratulations japanese kanji', '㊙️': 'secret japanese kanji', '🈴': 'passing grade japanese', '🈵': 'no vacancy full japanese',
  '🈹': 'discount japanese bargain', '🈲': 'prohibited japanese', '🈶': 'not free charge japanese', '🈚': 'free charge japanese',
  '🈸': 'application japanese', '🈺': 'open business japanese', '🈷️': 'monthly amount japanese', '🆎': 'ab blood type button',
  '🅰️': 'a blood type button', '🅱️': 'b blood type button', '🅾️': 'o blood type button',
};
